[package]
name = "typical90"
version = "0.1.0"
edition = "2021"

[[bin]]
name="1"
path="src/1_yokan.rs"

[[bin]]
name="2"
path="src/2_parentheses.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
