[package]
name = "abc385"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "a"
path = "src/a.rs"

[[bin]]
name = "b"
path = "src/b.rs"

[[bin]]
name = "c"
path = "src/c.rs"

[dependencies]
proconio = "0.5.0"
